#pragma once

#define DATA_PUBLISH_PERIOD_SECS 60
#define NETWORK_TIME_SYNC_HOURS 24

#define VIPER_LOCK D3
#define VIPER_UNLOCK D4
#define VIPER_REMOTE_START D5

#define VIPER_REMOTE_START_DURATION_SECS 12 * 60
#define VIPER_REMOTE_START_DELAY_UNTIL_NEXT_SECS 3 * 60
#define VIPER_REMOTE_START_MAX_STARTS_PER_SESSION 40

#include "const_auth.h"